import mongoose from "mongoose";

const agreementSchema = new mongoose.Schema(
  {
    agreementId: {
      type: String,
      required: true,
      unique: true,
    },
    status: {
      type: String,
      enum: ["Draft", "Sent", "Signed", "Active", "Completed", "Cancelled"],
      default: "Draft",
    },
    companyInfo: {
      companyName: { type: String, default: "Webflora Technologies" },
      companyAddress: { type: String, default: "IOC Colony, Kumhrar, Patna, 800026" },
      city: { type: String, default: "Patna" },
      state: { type: String, default: "Bihar" },
      country: { type: String, default: "India" },
      zipCode: { type: String, default: "800026" },
      email: { type: String, default: "hello.webflora@gmail.com" },
      phone: { type: String, default: "+91 8863081255" },
      alternatePhone: { type: String, default: "+91 8540814729" },
      gstNumber: { type: String, default: "" },
      cinNumber: { type: String, default: "" },
      website: { type: String, default: "www.webfloratechnologies.com" },
      logoUrl: { type: String, default: "" },
      authPersonName: { type: String, default: "Authorized Representative" },
      authPersonDesignation: { type: String, default: "Director" },
      companySignatureUrl: { type: String, default: "" },
    },
    clientInfo: {
      clientName: { type: String, required: true },
      companyName: { type: String, default: "" },
      address: { type: String, default: "" },
      city: { type: String, default: "" },
      state: { type: String, default: "" },
      country: { type: String, default: "" },
      zipCode: { type: String, default: "" },
      email: { type: String, required: true },
      phone: { type: String, default: "" },
      alternatePhone: { type: String, default: "" },
      gstNumber: { type: String, default: "" },
      clientDesignation: { type: String, default: "" },
    },
    projectInfo: {
      title: { type: String, required: true },
      projectCategory: { type: String, default: "" },
      projectType: {
        type: String,
        default: "Website Development",
      },
      description: { type: String, default: "" },
      techStack: [{ type: String }],
      featuresIncluded: [{ type: String }],
      deliverables: [{ type: String }],
      adminPanelIncluded: { type: Boolean, default: false },
      mobileAppIncluded: { type: Boolean, default: false },
      apiIntegration: { type: Boolean, default: false },
      hostingIncluded: { type: Boolean, default: false },
      seoIncluded: { type: Boolean, default: false },
      aiAutomationIncluded: { type: Boolean, default: false },
      maintenanceIncluded: { type: Boolean, default: false },
      cloudServicesIncluded: { type: Boolean, default: false },
    },
    timeline: {
      startDate: { type: Date },
      endDate: { type: Date },
      expectedDeliveryDate: { type: Date },
      milestones: [
        {
          title: { type: String },
          dueDate: { type: Date },
          amount: { type: Number },
        },
      ],
      deliveryTimeline: { type: String, default: "" },
      developmentTimeline: { type: String, default: "" },
      testingTimeline: { type: String, default: "" },
      deploymentTimeline: { type: String, default: "" },
      delayConditions: { type: String, default: "" },
    },
    payment: {
      totalCost: { type: Number, required: true, default: 0 },
      currency: { type: String, default: "INR" },
      advancePayment: { type: Number, default: 0 },
      midPayment: { type: Number, default: 0 },
      finalPayment: { type: Number, default: 0 },
      monthlyCharges: { type: Number, default: 0 },
      yearlyCharges: { type: Number, default: 0 },
      amcCharges: { type: Number, default: 0 },
      hostingCharges: { type: Number, default: 0 },
      seoCharges: { type: Number, default: 0 },
      gstPercentage: { type: Number, default: 18 },
      taxAmount: { type: Number, default: 0 },
      discount: { type: Number, default: 0 },
      latePaymentCharges: { type: String, default: "" },
      paymentTerms: { type: String, default: "" },
       refundPolicy: { type: String, default: "" },
      privacyPolicy: { type: String, default: "" },
      paymentMode: { type: String, default: "Bank Transfer" },
    },
    serviceCommitment: {
      commitmentRequired: { type: Boolean, default: false },
      commitmentType: {
        type: String,
        default: "No Commitment",
      },
      commitmentDuration: { type: String, default: "No Commitment" },
      lockInPeriod: { type: Number, default: 0 }, // in months
      lockInStartDate: { type: Date },
      earlyTerminationCharges: { type: String, default: "" },
      recoveryCharges: { type: String, default: "" },
      noticePeriod: { type: String, default: "" },
      renewalTerms: { type: String, default: "" },
      includedServices: [{ type: String }], // e.g., ["Hosting", "AMC"]
    },
    revisionSupport: {
      freeRevisions: { type: Number, default: 3 },
      freeSupportDuration: { type: String, default: "30 Days" },
      amcCharges: { type: Number, default: 0 },
      paidSupportTerms: { type: String, default: "" },
      extraRevisionCharges: { type: Number, default: 0 },
      bugFixSupport: { type: String, default: "" },
      emergencySupport: { type: String, default: "" },
      slaResponseTime: { type: String, default: "" },
    },
    clauses: [
      {
        clauseId: { type: String, required: true },
        title: { type: String, required: true },
        content: { type: String, required: true },
        enabled: { type: Boolean, default: true },
      },
    ],
    digitalSignature: {
      signatureData: { type: String, default: "" }, // Base64 visual signature drawn
      signedBy: { type: String, default: "" },
      signedAt: { type: Date },
      signStatus: { type: String, enum: ["Pending", "Signed"], default: "Pending" },
    },
    pdfFilePath: { type: String, default: "" },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "admin",
      required: true,
    },
    auditLogs: [
      {
        action: { type: String, required: true },
        timestamp: { type: Date, default: Date.now },
        adminName: { type: String, required: true },
      },
    ],
  },
  { timestamps: true }
);

export default mongoose.model("agreement", agreementSchema);
